name = "repopulse"
main = "src/index.ts"
compatibility_date = "2026-08-20"

[triggers]
crons = ["15 6 * * *"]

[[kv_namespaces]]
binding = "REPULSE_STATE"
id = "64f119ea8e2c4a9fb0aa70f8ba4602dc"
preview_id = "64f119ea8e2c4a9fb0aa70f8ba4602dc"
